exams = ['17 alfa – hidroxiprogesterona', 'a. fresco', 'a. fresco urina',
       'ácido acetil salicílico teste i', 'ácido fólico', 'ácido lático',
       'ácido úrico', 'ácido valpróico', 'acth', 'adenosina deaminase',
       'alanina aminotransferase (tgp)', 'albumina', 'aldolase',
       'aldosterona', 'alfa 1 antitripsina',
       'alfa 1 glicoproteína  ácida', 'alfa fetoproteína', 'amilase',
       'androstenediona', 'anfetamina', 'anti actina',
       'anti asca iga. ac anti-saccharomyces cerevisae',
       'anti asca igg. ac anti-saccharomyces cerevisae',
       'anti beta-2 glicoproteína  igg', 'anti beta-2 glicoproteína  igm',
       'anti cardiolipina igg', 'anti cardiolipina igm',
       'anti células parietais', 'anti centrômero',
       'anti descarboxilase do ácido glutâmico', 'anti esclero 70',
       'anti hbc igg', 'anti hbc igm', 'anti herpes simples (hsv)',
       'anti hiv ½ rápido', 'anti hiv ½ rápido para gestante',
       'anti hiv i e ii', 'anti hva igg', 'anti jo 1',
       'anti neuromielite  optica', 'anti parvovírus b19 (igg e igm)',
       'anti-endomísio', 'anti-gliadina  iga', 'anti-gliadina  igg',
       'anti-hbe', 'anti-hbs', 'anti-hcv', 'anti-hva (igm)',
       'anti-músculo  liso', 'anti-rnp', 'anti-sm', 'anti-tireoglobulina',
       'anticorpo anti-dna', 'anticorpo anti-mitocôndria',
       'anticorpo anti-ro (ssa)', 'anticorpo igg anti neuronio nuclea',
       'anticorpo la (ssb)', 'anticorpos contra vimentina',
       'antidepressivos tricíclicos teste i',
       'antidepressivos tricíclicos teste ii',
       'antidepressivos tricíclicos teste iii',
       'antiestreptolisina ‘o’ aso', 'antigenemia para citomegalovirus',
       'antígeno carcinoembrionário', 'antígeno hbeag', 'antígeno hbsag',
       'antiperoxidase', 'antiproteína  p ribossomal',
       'antitrombina  iii', 'aspartato aminotransferase (tgo)',
       'aspecto do líquor', 'atividade de renina', 'atividade proteína s',
       'avidezpara toxoplasmose', 'baciloscopia', 'bacterioscopia',
       'barbitúricos  teste i', 'barbitúricos  teste ii',
       'benzodiazepínicos teste ii', 'beta 2 microglobulina', 'beta hcg',
       'bilirrubina total e frações',
       'botulismo- pesquisa da toxina botulínica', 'ca 125', 'ca 15-3',
       'ca 19-9', 'cálcio', 'cálcio iônico', 'calcitonina',
       'cálculo urinário', 'capacidade de ligação do ferro livre',
       'capacidade de ligação do ferro total', 'carbamatos',
       'carbamazepina', 'carga viral', 'catecolaminas urinarias',
       'ceruloplasmina', 'chagas', 'chagas por elisa', 'chlamidia',
       'citologia', 'citomegalovírus igm', 'citomegalovírus igm',
       'citoquímica ferro medular', 'citoquímica p.a.s',
       'citoquímica sudan black', 'ck', 'ckmb', 'clearance de creatinina',
       'cloretos', 'clostridium difficile toxina (a e b)', 'cn c-anca',
       'cobre', 'cocaína teste i', 'cocaína teste ii', 'colesterol total',
       'colinesterase', 'complemento  c3', 'complemento  c4',
       'complemento  ch 50', 'contagem de linfócitos cd4/cd8',
       'coprocultura', 'coprológico  funcional simplificado', 'cortisol',
       'cortisol pós dexametasona', 'creatinina', 'crioaglutinina',
       'crioglobulinas', 'cultura',
       'cultura de fezes para campylobacter sp.', 'cultura de urina',
       'cultura para anaeróbio', 'cultura para baar',
       'cultura para bacilo diftérico',
       'cultura para bordetella pertussis (coq)', 'cultura para fungos',
       'cultura quantitativa', 'cultura vigilância - bgn',
       'curva de insulina pós glicose', 'd’dímero', 'densidade',
       'derivados anfetamínicos', 'desidrogenase lática', 'digoxina',
       'dosagem de chumbo', 'dosagem de ciclosporina',
       'dosagem de enzima conversora de a', 'dosagem de manganês',
       'dosagem de porfobilinogênio uri', 'dosagem de triptase',
       'dosagem de vitamina e', 'dosagem de zinco',
       'eletroforese  de proteínas', 'epstein baar virus - igg',
       'epstein baar vírus - igm', 'epstein barr vírus por pcr qualitati',
       'eritropoietina', 'espermograma', 'estradiol e2', 'etanol',
       'exame de urina de rotina', 'fan fator anti-nucleo (hep 2 cell)',
       'fator de v de leyden por pcr', 'fator reumatóide (látex)',
       'fenciclidina', 'fenitoína', 'fenobarbital', 'fenol',
       'fenotiazínicos', 'ferritina', 'ferro', 'fita adesiva',
       'fosfatase alcalina', 'fosfatase alcalina total e frações',
       'fósforo', 'fsh', 'fta-abs (igg)', 'fta-abs recombinado',
       'galactomanana', 'gama gt', 'gasometria arterial',
       'gasometria arterial de cordão', 'gasometria com lactato',
       'gasometria venosa', 'genotipagem  do hcv', 'glicose',
       'glicose pós-prandial', 'haptoglobina', 'hbv-dna quantitativo',
       'hcv- genotipagem', 'hcv-rna quantitativo', 'hdl-colesterol',
       'helicobacter  iga', 'helicobacter  igg', 'hemocultura',
       'hemocultura  anaeróbios', 'hemocultura  para fungos',
       'hemoglobina  glicada', 'herpes virus simples i por pcr',
       'herpes virus simples ii por pcr', 'hidrato de coral',
       'hiv imunoblot rápido', 'hla', 'homocisteína',
       'hormõnio de crescimento-gh', 'htlv i e ii', 'htlv i e ii por pcr',
       'htlv i/ii confirmatório', 'identificação  de carbamazepina',
       'identificação  de fragmentos/partes de helmintos', 'igf-1',
       'igfbp-3', 'imunoeletroforese de proteinas', 'imunofenotipagem',
       'imunoglobulina ‘a’', 'imunoglobulina ‘e’', 'imunoglobulina ‘g’',
       'imunoglobulina ‘m’', 'imunoglobulina e para leite de vaca',
       'índice cálcio / creatinina',
       'índice de gemulação criptococcus neoformans',
       'índice proteína / creatinina', 'insulina',
       'isolamento viral para dengue', 'látex para criptcoccus',
       'látex para germes comuns', 'ldl-colesterol', 'leptospirose', 'lh',
       'lipase', 'lítio', 'lkm1', 'maconha teste i', 'maconha teste ii',
       'magnésio', 'metahemoglobina', 'metanefrinas  urinarias',
       'metanfetamina', 'micológico direto', 'microalbuminúria',
       'monoteste', 'mutação do gem da protrombina  g20',
       'nitrogênio uréico', 'opioides', 'organofosforados',
       'osmolaridade  sérica', 'osmolaridade  urinária', 'p-anca',
       'paracetamol  teste i', 'paracetamol  teste ii', 'paraquat/diquat',
       'parasitológico com saf', 'parasitológico de fezes',
       'paratormônio', 'pcr para citomegalovirus (qualitat',
       'pcr para citomegalovirus (quantita', 'pcr para hla b27',
       'pcr qualitativa para micobactérias', 'peptídeo c',
       'pesquisa da t(15;17)', 'pesquisa da t(8;21)',
       'pesquisa da t(9;22)(q34;q11)  bcr/abl p190',
       'pesquisa da t(9;22)(q34;q11)  bcr/abl p210',
       'pesquisa de astrovírus/ norovírus', 'pesquisa de baar',
       'pesquisa de bacilo diftérico', 'pesquisa de bacilo ducrey',
       'pesquisa de campylobacter', 'pesquisa de corpos cetônicos',
       'pesquisa de criptococcus', 'pesquisa de criptosporidium',
       'pesquisa de cristais', 'pesquisa de doença de lyme-simile',
       'pesquisa de fungos', 'pesquisa de fungos por imunodifus',
       'pesquisa de gordura fecal', 'pesquisa de h1n1/influenza a',
       'pesquisa de hantavirose  (igg e igm)',
       'pesquisa de hematozoários', 'pesquisa de inv 16',
       'pesquisa de isospora belli', 'pesquisa de larvas',
       'pesquisa de leishmania', 'pesquisa de leucócitos fecais',
       'pesquisa de macroprolactina', 'pesquisa de micoplasma',
       'pesquisa de mobiluncus', 'pesquisa de mutação flt3-d835',
       'pesquisa de mutação flt3-dit', 'pesquisa de mutação jak2v617f',
       'pesquisa de neisseria gonorrhoeae',
       'pesquisa de pneumocystis  carinii', 'pesquisa de rotavírus',
       'pesquisa de sangue oculto', 'pesquisa de schistossoma  mansoni',
       'pesquisa de streptococcus agalactiae',
       'pesquisa de trichomonas  fecalis', 'pesquisa de trofozoítos',
       'pesquisa de ureaplasma', 'pesquisa de viroses respiratórias',
       'pesquisa de virus sarampo/ rubéola',
       'pesquisa e dismorfismo  eritrocitá',
       'pesquisa para febre maculosa', 'potássio',
       'potencial hidrogeniônico', 'potencial hidrogeniônico fecal',
       'pró-bnp', 'procalcitonina', 'progesterona',
       'proteina c funcional', 'proteína c reativa ultra sensível',
       'proteína de bence jones', 'proteínas totais',
       'proteínas totais e frações', 'proteinúria',
       'prova de waaler-rose', 'psa livre', 'psa total',
       'quantificação  do antigeno fator de von willebrand',
       'reação de widal', 'resistencia a proteína c ativada',
       'rubéola (igg)', 'rubéola (igm)', 'shbg',
       'sorologia para bartonella', 'sorologia para brucelose',
       'sorologia para caxumba', 'sorologia para cisticercose',
       'sorologia para dengue', 'substâncias redutoras', 'sulfato dhea',
       'swab anal', 't3 livre', 't3 reverso', 't3 total', 't4 livre',
       't4 total', 'tacrolimus', 'tempo de tromboplastina parcial c',
       'tempo e atividade de protrombina', 'teofilina',
       'teste de estímulo do gh após clonidina',
       'teste de estímulo do gh após insulina', 'teste de falcização',
       'teste de ham', 'teste de resistência  osmótica a 0.36',
       'teste de supressão do hgh após glicose',
       'teste oral de tolerância a glicose',
       'teste oral de tolerância a glicose 100g',
       'teste oral de tolerância a glicose 50g',
       'teste oral de tolerância a glicose 75g',
       'teste oral de tolerância a glicose 75g\nmodificado',
       'teste oral de tolerância a lactose', 'testosterona  livre',
       'testosterona  total', 'tinta da china', 'tireoglobulina',
       'toxoplasmose  (igg)', 'toxoplasmose  (igm)', 'transferrina',
       'transglutaminase iga', 'triagem drogas de abuso',
       'triglicerídeos', 'tromboplastina parcial ativada mix',
       'troponina i', 'tsa', 'tsh', 'tuberculina  purificada (mantoux)',
       'uréia', 'vdrl', 'vdrl para gestante', 'veta hcg quantitativo',
       'vitamina b12', 'vitamina d- 1,25 dihidroxicolecalciferol',
       'vitamina d-25-hidroxi', 'vldl']

def parce(lines):
    pass

